### ISSUE TITLE
android: low-latency scan support

### ISSUE THREAD

**Issue by Dirbaio** [alexmoon/bluest#14]
Scan by default on Android is quite slow to preserve power. You have to request a ["low latency" scan mode](https://developer.android.com/reference/android/bluetooth/le/ScanSettings#SCAN_MODE_LOW_LATENCY) to get decent speed.

Currently bluest API has no way to specify scan settings. What do we do?

- Hardcode the low latency mode?
- Extend the API somehow with platform-specific scan settings...?

**Comment by alexmoon** [comment]
The general philosophy of Bluest is to try and support consistent behavior across platforms to the greatest extent possible. The scan settings and filtering are particularly variable across the different APIs. In the interest of consistency, I'd recommend we just hardcode low latency mode to match the other platforms.
