### ISSUE TITLE
 Negotiating or Viewing MTU Settings

### ISSUE THREAD

**Issue by Rust-Trends** [alexmoon/bluest#19]
Hi everyone,

I wanted to ask if there’s a way to negotiate the MTU (Maximum Transmission Unit) on a connection, or if it’s at least possible to see what the MTU is currently set to. Any advice or insights on how to manage or view this would be greatly appreciated.

Thanks in advance for your help!

Best regards,
Bob

**Comment by alexmoon** [comment]
You can get the MTU by calling `max_write_len` on a characteristic. Most Bluetooth APIs don't provide any facility for userspace to re-negotiate the MTU selected by the OS.

**Comment by Rust-Trends** [comment]
Thank you, @alexmoon, for the explanation. I didn’t consider that max_write_len represents the actual MTU. I was under the impression that the desired MTU could be negotiated, as is possible in Android with FlutterBlue, which led to my incorrect assumption.
