### ISSUE TITLE
How to Use Stream Discover Device (Help)

### ISSUE THREAD

**Issue by ekokurniadi** [alexmoon/bluest#2]
Hi, i am a really new in rust and i try to use this library on my flutter project, everything is work, but i have a problem, how to use stream on discovering ble device ? would you mind to added a little example please. Thank you

**Comment by alexmoon** [comment]
The scan example in the examples folder shows how to use it.

**Comment by ekokurniadi** [comment]
Hi, Thanks for your response, the scan example is working correctly, but i want to add timeout after 10 second, how can i do ? i really new in rust

**Comment by alexmoon** [comment]
That’s a general async rust question. Trey searching for async rust timeout.
