### ISSUE TITLE
An error was encountered while compiling iOS

### ISSUE THREAD

**Issue by reformc** [alexmoon/bluest#20]
I wrote a crate, which works fine on macos (M2), but with an error when compiling to iPhone using tauri.

Undefined symbols for architecture arm64:
  "_CBAdvertisementDataIsConnectable", referenced from:
      bluest::corebluetooth::types::_$LT$impl$u20$bluest..AdvertisementData$GT$::from_nsdictionary::h40696a5a1084144b in libapp.a[174](bluest-ce3a53bf51f8bb28.bluest.d85386fe352b9c42-cgu.0.rcgu.o)
  "_CBAdvertisementDataLocalNameKey", referenced from:
      bluest::corebluetooth::types::_$LT$impl$u20$bluest..AdvertisementData$GT$::from_nsdictionary::h40696a5a1084144b in libapp.a[174](bluest-ce3a53bf51f8bb28.bluest.d85386fe352b9c42-cgu.0.rcgu.o)
  "_CBAdvertisementDataManufacturerDataKey", referenced from:
      bluest::corebluetooth::types::_$LT$impl$u20$bluest..AdvertisementData$GT$::from_nsdictionary::h40696a5a1084144b in libapp.a[174](bluest-ce3a53bf51f8bb28.bluest.d85386fe352b9c42-cgu.0.rcgu.o)
  "_CBAdvertisementDataOverflowServiceUUIDsKey", referenced from:
      bluest::corebluetooth::types::_$LT$impl$u20$bluest..AdvertisementData$GT$::from_nsdictionary::h40696a5a1084144b in libapp.a[174](bluest-ce3a53bf51f8bb28.bluest.d85386fe352b9c42-cgu.0.rcgu.o)
  "_CBAdvertisementDataServiceDataKey", referenced from:
      bluest::corebluetooth::types::_$LT$impl$u20$bluest..AdvertisementData$GT$::from_nsdictionary::h40696a5a1084144b in libapp.a[174](bluest-ce3a53bf51f8bb28.bluest.d85386fe352b9c42-cgu.0.rcgu.o)
  "_CBAdvertisementDataServiceUUIDsKey", referenced from:
      bluest::corebluetooth::types::_$LT$impl$u20$bluest..AdvertisementData$GT$::from_nsdictionary::h40696a5a1084144b in libapp.a[174](bluest-ce3a53bf51f8bb28.bluest.d85386fe352b9c42-cgu.0.rcgu.o)
  "_CBAdvertisementDataTxPowerLevelKey", referenced from:
      bluest::corebluetooth::types::_$LT$impl$u20$bluest..AdvertisementData$GT$::from_nsdictionary::h40696a5a1084144b in libapp.a[174](bluest-ce3a53bf51f8bb28.bluest.d85386fe352b9c42-cgu.0.rcgu.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

If I remove the Bluetooth call, it compiles to the iPhone and runs fine.

**Comment by alexmoon** [comment]
Make sure you're linking your app with the Core Bluetooth framework.

**Comment by reformc** [comment]
It works. Thanks
