### ISSUE TITLE
ERROR bluest::windows::adapter: Unable to send AdvertisingDevice: TrySendError { kind: Full }

### ISSUE THREAD

**Issue by davehorner** [alexmoon/bluest#24]
I am getting many errors that look like this:
```
ERROR bluest::windows::adapter: Unable to send AdvertisingDevice: TrySendError { kind: Full }
```

This is happening with the latest on windows 11.
I have tried up'ing the channels; doesn't seem to make difference.
```
    pub async fn scan<'a>(
        &'a self,
        services: &'a [Uuid],
    ) -> Result<impl Stream<Item = AdvertisingDevice> + Send + Unpin + 'a> {
        let (sender, receiver) = futures_channel::mpsc::channel(128); <--- tried increasing
        let sender = Arc::new(std::sync::Mutex::new(sender));

        let weak_sender = Arc::downgrade(&sender);
        let received_handler = TypedEventHandler::new(
            move |watcher: &Option<BluetoothLEAdvertisementWatcher>,
                  event_args: &Option<BluetoothLEAdvertisementReceivedEventArgs>| {
                if let Some(sender) = weak_sender.upgrade() {
                    if let Some(event_args) = event_args {
                        let res = sender.lock().unwrap().try_send(event_args.clone());
                        if let Err(err) = res {
                            error!("Unable to send AdvertisingDevice: {:?}", err);   <--- the error of concern.
                        }
                    }
                } else if let Some(watcher) = watcher {
                    let res = watcher.Stop();
                    if let Err(err) = res {
                        warn!("Failed to stop BluetoothLEAdvertisementWatcher: {:?}", err);
                    }
                }
                Ok(())
            },
        );
```
the application continues to process advertisements in between errors and it seems to degrade performance or seems to stutter.

**Comment by davehorner** [comment]
Ok(receiver
            .filter(move |event_args| {
         // Check if event_args contain valid manufacturer data for company ID 0x0059
         if let Some(advertisement) = event_args.Advertisement().ok() {
            match advertisement.GetManufacturerDataByCompanyId(0x0059) {
                Ok(manufacturer_data) => {
                    // Optionally log or inspect manufacturer_data if needed
                    return manufacturer_data.Size()!=Ok(0);
                }
                Err(_) => false, // Filter out if there's an error getting manufacturer data
            }
        } else {
            false // Filter out if Advertisement is None
        }
            })
            .then(move |event_args| {
                let _guard = &guard;

make that more succint

**Comment by davehorner** [comment]
```
        Ok(receiver
            .filter(move |event_args| {
                event_args.Advertisement()
                    .ok()
                    .and_then(|ad| ad.GetManufacturerDataByCompanyId(0x0059).ok())
                    .map_or(false, |data| data.Size() != Ok(0))
            })
            .then(move |event_args| {
                let _guard = &guard;

                Box::pin(async move {

```
There's a lot of messages and processing each of them is too much.  I added a filter which needs to be in scan.

are you open to another scan method that takes a company_id or an optional?
maybe a 
```
pub async fn scan<'a>(
    &'a self,
    services: &'a [Uuid],
    company_id: Option<u16>, // Add company_id as an optional parameter
) -> Result<impl Stream<Item = AdvertisingDevice> + Send + Unpin + 'a> {
```

and then this would become something like:
```
    Ok(receiver
        .filter(move |event_args| {
            // Filter based on company_id if provided
            if let Some(cid) = company_id {
                event_args.Advertisement()
                    .ok()
                    .and_then(|ad| ad.GetManufacturerDataByCompanyId(cid).ok())
                    .map_or(false, |data| data.Size() != Ok(0))
            } else {
                // If no company_id is provided, allow all advertisements
                true
            }
        })
        .then(move |event_args| {
```

another option might be to pass a filter functions.
```
type FilterFn = Box<dyn Fn(&BluetoothLEAdvertisementReceivedEventArgs) -> bool + Send + Sync>;

pub async fn scan<'a>(
    &'a self,
    services: &'a [Uuid],
    filters: Vec<FilterFn>, // Accept a vector of filter functions
) -> Result<impl Stream<Item = AdvertisingDevice> + Send + Unpin + 'a> {
.
.
    Ok(receiver
        .filter(move |event_args| {
            // Apply each filter function to the event
            filters.iter().all(|filter| filter(event_args))
        })
        .then(move |event_args| {
 .
 .
 let scan_filters: Vec<FilterFn> = vec![
    Box::new(|args: &BluetoothLEAdvertisementReceivedEventArgs| {
        // Filter by company ID
        args.Advertisement()
            .ok()
            .and_then(|ad| ad.GetManufacturerDataByCompanyId(0x0059).ok())
            .map_or(false, |data| data.Size() != Ok(0))
    }),
    Box::new(|args: &BluetoothLEAdvertisementReceivedEventArgs| {
        // Filter based on RSSI threshold
        args.RawSignalStrengthInDBm().ok().map_or(false, |rssi| rssi > -70)
    }),
];

let stream = scan(&[], scan_filters).await?;
```
couple ways to skin a cat.

**Comment by alexmoon** [comment]
That error should probably be changed to a warning, or even info. It just means that some advertisements are being dropped because the consumer of the stream is not keeping up.

We only have filtering on service UUIDs because that is the only filtering option available in CoreBluetooth. Windows and Linux do support further filtering options but if we exposed them they would not work on iOS/MacOS.

You can filter the stream yourself using `.filter` on the returned `Stream`. On Windows, we do have to use an async API to get the `BluetoothLEDevice` corresponding to a Bluetooth address, but that operation should be very fast relative to the rate of advertisement events.

Most likely, if you're seeing this error it is due to the time it takes you to process the advertisements in your application code. If your processing of the stream items takes a significant amount of time (on the order of tens to hundreds of milliseconds), that can cause the stream to back up and become full. If that's the case, you can try moving your processing to a separate task or using something like `ConcurrentStream` from `futures-concurrency` to process multiple items concurrently. Or you can simply ignore the error if you don't need to see every advertisement.

**Comment by davehorner** [comment]
That's I thought I implemented with the filter above (filtering it myself) and should be cross-platform?  Surprised to find the other platforms wouldn't filter on such a field.  I believe that string for the error is used twice; it would be nice to have different messages for different errors.

**Comment by alexmoon** [comment]
I'm saying you can do that filtering in your application code, there's no need for it to be in bluest.

The platform-specific filtering filters the advertisement events at the driver level preventing the events from being generated in the first place. It has distinct quirks on each platform.

**Comment by davehorner** [comment]
It's sorta a basic need for BLE advertisements and seems like it belongs in bluest IMHO.  Ok.
